### ISSUE TITLE
Dica para criar interfaces

### ISSUE THREAD

**Issue by jaelsonsantos1** [Los-had/Password_generator-By-Los-had#1]
olá, vi em seu código que você mencionou que não sabe criar interfaces, eu te indico uma biblioteca super simples completa e prática para criação de interface, o nome da biblioteca é PyQt5 ou PySide2 que são quase iguais, o bom dessa biblioteca é que ela vem com uma ferramenta para facilitar ainda mais a criação da GUI, onde você pode criar sua interface apenas arrastando os componentes para tela, sem precisar programar manualmente!
[Documentação do PySide2](https://pypi.org/project/PySide2/)
[Documentação do PyQt5](https://pypi.org/project/PyQt5/)

e esse é o QtDisigner:
![print](https://user-images.githubusercontent.com/80257886/114725211-b36a6a80-9d12-11eb-83b8-a59cfcdbf2be.png)

**Comment by Los-had** [comment]
Olá @jaelsonsantos1, muito obrigado pela excelente dica, estou imensamente agradecido por essa ajuda que você me deu, vou olhar sim essa opção pois não tenho muito conhecimento com interface gráfica.

Obrigado por contribuir com projeto!

**Comment by jaelsonsantos1** [comment]
Que isso, no que eu puder ajudar eu ajudo 👊

**Comment by Los-had** [comment]
> Que isso, no que eu puder ajudar eu ajudo 👊

Obg
